AWSTemplateFormatVersion: '2010-09-09'
Description: "Instancia EC2 para servidor web Proyecto Meli"

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Acceso SSH y HTTP
      VpcId: !ImportValue VPC-proyecto-Meli
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: EC2SecurityGroup

  EC2Instance: "Servidor-web-proyecto-Meli"
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      KeyName: Key-Proyecto-Meli
      ImageId: ami-092cd6a84ad570057
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeviceIndex: 0
          SubnetId: !ImportValue PublicSubnet1-proyecto-Meli
          GroupSet:
            - !Ref InstanceSecurityGroup
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 8
            VolumeType: gp3
            DeleteOnTermination: true
      Tags:
        - Key: Servidor-Web-Proyecto-Meli
          Value: InstanciaEC2-Meli

Outputs:
  InstanceId:
    Description: Servidor-Web-Proyecto-Meli
    Value: !Ref EC2Instance

  PublicIP:
    Description: IP pública asignada
    Value: !GetAtt EC2Instance.PublicIp
