Resources:
   MiServidorWebEC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-092cd6a84ad570057"
      KeyName: "Key-Proyecto-Meli" 
      InstanceType: "t2.micro"
      BlockDevIceMapping:
         DeviceName:"/dev/ssh"
         Ebs:
            VolumeType:"gp3"
            DeleteOnTermination: "true"
            VolumeSize: "10"
    
      Tags:
        - Key: "MiServidorWebEC2"
          Value: "EC2-instance-Meli"
