Resources:
   MiServidorWebEC2:
    Type: "AWS::EC2::Instance"
    Properties:
      ImageId: "ami-092cd6a84ad570057"
      KeyName: "Key-Proyecto-Meli" 
      InstanceType: "t2.micro" 
      Tags:
        - Key: "MiServidorWebEC2"
          Value: "EC2-instance-Meli"
